### ISSUE TITLE
Duplicated copy step in yocto and image maker

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-parallella#1]
Image maker uses the coffee (json) file. This file defines an unconditional copy operation as it follows:

```
            command: 'copy'
            from:
                partition:
                    primary: 1
                path: '/device-trees/parallella-mmc-boot.dtb'
            to:
                partition:
                    primary: 1
                path: '/devicetree.dtb'
```

In the same time, yocto, at image generation does the same thing:

https://github.com/resin-os/resin-parallella/blob/master/layers/meta-resin-parallella/recipes-core/images/resin-image.bbappend

`device-trees/parallella-mmc-boot.dtb:/devicetree.dtb \`

This means that we duplicate the same operation uselessly.

Solution: remove the operation from coffee file and let yocto manage this copy.
